### ISSUE TITLE
Highlight big breaking changes?

### ISSUE THREAD

**Issue by Minishlink** [react-native-community/react-native-releases#6]
Hey :)

Thanks for taking the time to write such detailed changelogs, it helps a lot! Here's a small feedback on latest changelog (0.54):

It would be great to highlight the big breaking changes, for example:

- **[BREAKING]** Delete RCTBatchedBridge

**Comment by turnrye** [comment]
Hey @Minishlink, thanks for the feedback! The "Removed" section represents only removed features, not just instances of removed code. This is consistent with [Keep a Changelog 1.0.0](http://keepachangelog.com/en/1.0.0/). Everything present in that section is a breaking change. I'll make sure to add a detail going forward in that heading clarifying that they are breaking, since I think that's a keyword that lots of people key off of. Thanks again – this sort of feedback is exactly what we need. Please reopen if there are additional thoughts.
