### ISSUE TITLE
Issue Placeholder Template

### ISSUE THREAD

**Issue by renalpraba** [react-native-community/react-native-releases#92]
I have a suggestion by creating issue placeholder template saying what to do with this repository and giving options when this is not the place to post issue, to keep this repository only with relevant issues, does it necessary?

**Comment by hramos** [comment]
That'd be a good idea. For anyone interested in sending a PR, you can take a look at how the core repository is set up: https://github.com/facebook/react-native/tree/master/.github

Adding a single `ISSUE_TEMPLATE.md` to a `.github` directory should be enough, especially if we're not expecting people other than release maintainers to open issues. Otherwise, we could also look into providing multiple issue templates (look at the issue template sub-directory linked above).

**Comment by kelset** [comment]
I guess we could...? But this repo is not meant for creating issues aside from the ones we create for the releases?

It could probably say "if you are reading this, probably you should not be posting an issue here" and some links to other repo?

**Comment by hramos** [comment]
Pointing people elsewhere is what I had in mind, with a single issue_template.md.

**Comment by kelset** [comment]
PR -> https://github.com/react-native-community/react-native-releases/pull/94/
